[package]
name        = "sentinel-mir"
description = "SSA-form mid-level IR with optimizations"

edition.workspace      = true
rust-version.workspace = true
version.workspace      = true
authors.workspace      = true
license.workspace      = true
repository.workspace   = true

[dependencies]
sentinel-ast   = { path = "../sentinel-ast" }
sentinel-types = { path = "../sentinel-types" }

[lints.rust]
unsafe_code = "deny"