[package]
name        = "sentinel-ast"
description = "Abstract syntax tree types for Sentinel source"

edition.workspace      = true
rust-version.workspace = true
version.workspace      = true
authors.workspace      = true
license.workspace      = true
repository.workspace   = true

[dependencies]
tracing    = { workspace = true }
thiserror  = { workspace = true }

[lints.rust]
unsafe_code = "deny"
