[package]
name        = "sentinel-syntax"
description = "Lexer, parser, and concrete syntax tree for Sentinel source"

edition.workspace      = true
rust-version.workspace = true
version.workspace      = true
authors.workspace      = true
license.workspace      = true
repository.workspace   = true

[dependencies]
sentinel-ast  = { path = "../sentinel-ast" }
sentinel-base = { path = "../sentinel-base" }

logos      = { workspace = true }
miette     = { workspace = true }
salsa      = { workspace = true }
thiserror  = { workspace = true }
tracing    = { workspace = true }

[dev-dependencies]
insta      = { workspace = true }

[lints.rust]
unsafe_code = "deny"
