[package]
name        = "sentinel-resolve"
description = "Name resolution, module graph, and import handling"

edition.workspace      = true
rust-version.workspace = true
version.workspace      = true
authors.workspace      = true
license.workspace      = true
repository.workspace   = true

[dependencies]
sentinel-ast    = { path = "../sentinel-ast" }
sentinel-base   = { path = "../sentinel-base" }
sentinel-syntax = { path = "../sentinel-syntax" }

miette     = { workspace = true }
salsa      = { workspace = true }
thiserror  = { workspace = true }
tracing    = { workspace = true }

[lints.rust]
unsafe_code = "deny"