[package]
name        = "sentinel-types"
description = "Type, region, nullability, secrecy, and effect checking"

edition.workspace      = true
rust-version.workspace = true
version.workspace      = true
authors.workspace      = true
license.workspace      = true
repository.workspace   = true

[dependencies]
sentinel-ast     = { path = "../sentinel-ast" }
sentinel-base    = { path = "../sentinel-base" }
sentinel-resolve = { path = "../sentinel-resolve" }
sentinel-syntax  = { path = "../sentinel-syntax" }

miette     = { workspace = true }
salsa      = { workspace = true }
thiserror  = { workspace = true }
tracing    = { workspace = true }

[lints.rust]
unsafe_code = "deny"
