[package]
name        = "sentinel-codegen"
description = "LLVM IR lowering via inkwell"

edition.workspace      = true
rust-version.workspace = true
version.workspace      = true
authors.workspace      = true
license.workspace      = true
repository.workspace   = true

[dependencies]
sentinel-ast = { path = "../sentinel-ast" }

inkwell    = { workspace = true }
miette     = { workspace = true }
thiserror  = { workspace = true }
tracing    = { workspace = true }

[lints.rust]
unsafe_code = "allow"
