[package]
name        = "sentinel-codegen"
description = "LLVM IR lowering via inkwell"

edition.workspace      = true
rust-version.workspace = true
version.workspace      = true
authors.workspace      = true
license.workspace      = true
repository.workspace   = true

[dependencies]
sentinel-ast          = { path = "../sentinel-ast" }
sentinel-borrow-check = { path = "../sentinel-borrow-check" }
sentinel-hir          = { path = "../sentinel-hir" }
sentinel-resolve      = { path = "../sentinel-resolve" }
sentinel-types        = { path = "../sentinel-types" }

inkwell    = { workspace = true }
miette     = { workspace = true }
thiserror  = { workspace = true }
tracing    = { workspace = true }

[dev-dependencies]
sentinel-syntax = { path = "../sentinel-syntax" }

[lints.rust]
unsafe_code = "allow"
